# Generated by Django 4.1.2 on 2022-11-01 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=200)),
                ('arrive', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('date', models.CharField(max_length=200)),
                ('heure', models.CharField(max_length=200)),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vol.trajet')),
            ],
        ),
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='')),
                ('vols', models.ManyToManyField(to='Vol.vol')),
            ],
        ),
    ]
