# Generated by Django 4.1.4 on 2022-12-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vol", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="compagnie", name="vols",),
        migrations.AddField(
            model_name="vol",
            name="compagnies",
            field=models.ManyToManyField(to="Vol.compagnie"),
        ),
    ]
