# Generated by Django 4.1.4 on 2022-12-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vol", "0002_remove_compagnie_vols_vol_compagnies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compagnie",
            name="logo",
            field=models.ImageField(upload_to="logoFiles"),
        ),
    ]
